/**
 * Perform compendium redirects from premium content UUIDs to BFRD UUIDs if content isn't enabled.
 */
export function _configureRedirects() {
	for (const [id, map] of Object.entries(mappings)) {
		if (game.modules.get(id)?.active) continue;
		Object.assign(CONFIG.compendium.uuidRedirects, map);
	}
}

const mappings = {
	"kp-tov-monster-vault": {
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.rjTvRRXk5fYm7I2A":
			"Compendium.black-flag.npcs.Actor.0HVNfNw8FH86Okt2",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.enOvZ0mSQM9wof8C":
			"Compendium.black-flag.npcs.Actor.0JZiKg6CAIMLtZH8",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.bTEmBJqxeUIVPuo3":
			"Compendium.black-flag.npcs.Actor.0K5CxUDUiujeakgk",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Dbpd9MMe1OaMZmTf":
			"Compendium.black-flag.npcs.Actor.0Mg4V0kejtIaabNH",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.tlUZfdwZ6hAehA28":
			"Compendium.black-flag.npcs.Actor.0V3Lr3QRumobWHx0",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ZcHoYyg5pRSMQTQn":
			"Compendium.black-flag.npcs.Actor.17IBYn92WaO4cpZV",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.VjOYBpVmVIGXBrYG":
			"Compendium.black-flag.npcs.Actor.18raGcNxoTnhNR4e",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.zf4FJXjcJAmdwj6D":
			"Compendium.black-flag.npcs.Actor.1DE36RiFP9m36ArE",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.gquf11NznYRqOGsH":
			"Compendium.black-flag.npcs.Actor.1G7XY0ZB4uyZ3nmq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.dmhQoMojRRfBqC5u":
			"Compendium.black-flag.npcs.Actor.1yxIUY2PhIB0JL6F",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.xzNkh19gS47k8afx":
			"Compendium.black-flag.npcs.Actor.258vx22WFSTFOm89",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.eEAXziz8XtFZ3nzF":
			"Compendium.black-flag.npcs.Actor.2DCblylWLteSqQ07",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.WsRWRaPKfLxqEoPF":
			"Compendium.black-flag.npcs.Actor.2Uyw9ZrqRJur5bwE",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.OqxTARVO2L9pnp8E":
			"Compendium.black-flag.npcs.Actor.2fm38cdINKCumyVe",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.5vnQLJvpGCK6Xd3G":
			"Compendium.black-flag.npcs.Actor.2jjHoh5gIkTX9UJh",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.qL9i20vF4fhV0HEX":
			"Compendium.black-flag.npcs.Actor.2kfljh07dG03TyFw",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.IrCppwl32Eh1x3eB":
			"Compendium.black-flag.npcs.Actor.30cQKcGgU756PTGc",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.wSdGAr8dgNapGEy0":
			"Compendium.black-flag.npcs.Actor.38E3bpoPnOg2DVJg",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ha3bnaIj7LunHO3k":
			"Compendium.black-flag.npcs.Actor.3OZjOK8mayQUCVGq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.40kqb3AQkrtccwLS":
			"Compendium.black-flag.npcs.Actor.3TQoqyumjGWMNY8A",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ITN3FquhYychsRtp":
			"Compendium.black-flag.npcs.Actor.3kWX8wTv3jSx6Eip",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.f0ChPe9ka5Oj527N":
			"Compendium.black-flag.npcs.Actor.3pxse6nO7eDOzBcW",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.fIIoyvy7gfJ5RkGo":
			"Compendium.black-flag.npcs.Actor.42AgwMUryk85tzJH",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.g6jt98ZIbZYHkCkH":
			"Compendium.black-flag.npcs.Actor.44drnXUj8btZkBGo",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.xM3mRZBcUVAgBkPh":
			"Compendium.black-flag.npcs.Actor.4CrFraJ1x2kGXq8m",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.M924d7xV1m3yfY1B":
			"Compendium.black-flag.npcs.Actor.4NUA3TSPsgFOuw9u",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.IJdyJCqfn6aI505u":
			"Compendium.black-flag.npcs.Actor.4PpHHnBivDwDPaSG",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.7e3SS1Mjoapo1mcN":
			"Compendium.black-flag.npcs.Actor.4Qkpm6O4vpdLLHUr",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.KzY2NPwgBCezJzzk":
			"Compendium.black-flag.npcs.Actor.50j1gqWnNtKO7X0d",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.vkhLYJsFYo5eUmei":
			"Compendium.black-flag.npcs.Actor.6KZkDgmaA18V8VQa",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.lOWajmXJhPGe2Lh5":
			"Compendium.black-flag.npcs.Actor.6O7aWmTPxvS8onm6",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.pEygHFdyqtSneUEf":
			"Compendium.black-flag.npcs.Actor.6W5ONcmLafNXxgp1",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.tjiu1CY6XEBIYF4a":
			"Compendium.black-flag.npcs.Actor.6aHtiu1tmyE9zRkJ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.T6Y9t1QIhVkuF3bq":
			"Compendium.black-flag.npcs.Actor.6iYSh1A8TVKlGH7D",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.OTlZsWBqV6F2L1zU":
			"Compendium.black-flag.npcs.Actor.6pw2lqbPkMvsrPOK",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.SOAK3SDQ3c7MsSIM":
			"Compendium.black-flag.npcs.Actor.720AD4nxM0Gc6OYk",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.QEkn4dWZyNdKZ8HA":
			"Compendium.black-flag.npcs.Actor.7DTd6bSfeGM62mkz",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.aRW9QRVHO3YrEmyo":
			"Compendium.black-flag.npcs.Actor.7VfZiocWIMOANfjs",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sEozPuP4TJCeQUd8":
			"Compendium.black-flag.npcs.Actor.7VmFAXDknLqyUSQH",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.M9SO7NuHcRo7MIoI":
			"Compendium.black-flag.npcs.Actor.7iAgwX9bFGLZSwhf",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.1lE2yWVl8kpG2f0G":
			"Compendium.black-flag.npcs.Actor.7o3c60QL0eOzwgbw",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.vWKlM4EMHEdnCeuD":
			"Compendium.black-flag.npcs.Actor.7ug5ZKvOZ6YrRxUJ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.6gpJXdD0yisigJHl":
			"Compendium.black-flag.npcs.Actor.8ZGw45FNU52DyRyf",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Mwhkv4yinQUCG3Ly":
			"Compendium.black-flag.npcs.Actor.90gAvpMg83KhqRdh",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HSZcrK1zHXlSQV25":
			"Compendium.black-flag.npcs.Actor.99a2Tu4HoGWQT7cQ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.88mj0DVWeZNbpcdx":
			"Compendium.black-flag.npcs.Actor.9MiXuSE9adOdqXSh",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.eFwwMKxLYn9d2wQ1":
			"Compendium.black-flag.npcs.Actor.9i7BxxS2qSNRAoFU",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HKMbXJBhJwyTM3yC":
			"Compendium.black-flag.npcs.Actor.9lP9jFwc6Ib2XcKv",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.S3T9ofMkM1h8CG4E":
			"Compendium.black-flag.npcs.Actor.AA2C6GyHE5bJ9IQb",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.KxVVm8AwJ0yc8ajg":
			"Compendium.black-flag.npcs.Actor.AVUy5QORsFknY1cl",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.phz06mVnAbtiArlc":
			"Compendium.black-flag.npcs.Actor.Ab3rAgIxsyfZi3Bw",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.TW6wjoCey2SYQouC":
			"Compendium.black-flag.npcs.Actor.AbtSnvjVHTDzZciV",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.tyALSoc25e5GDDQD":
			"Compendium.black-flag.npcs.Actor.Ae67uuF7mBe8NGDN",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.DKAEalKU31jRB9d1":
			"Compendium.black-flag.npcs.Actor.AhQGKYIaDvfyO09q",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.9Wq3qyFB3H8wYFB2":
			"Compendium.black-flag.npcs.Actor.Al2A3NEedXjtvwb6",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.t75FujoFBxZyrqms":
			"Compendium.black-flag.npcs.Actor.AqapgXTjbGNI08sZ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.pMKupJjIGbSNLSuy":
			"Compendium.black-flag.npcs.Actor.AvBMFHvsEuWp70t6",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.MzKEuWIUSKUY64Mr":
			"Compendium.black-flag.npcs.Actor.BKeSIam1C0mXCW3s",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.p421h7yYH3XgDtTc":
			"Compendium.black-flag.npcs.Actor.BLi3PwiKwa4TVWVB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.0yzHkdrMED9Ms2dr":
			"Compendium.black-flag.npcs.Actor.BMQmretRxYzJOeeV",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sGR4gEstTMNswYI1":
			"Compendium.black-flag.npcs.Actor.BZwfOqKD0mlStI12",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HnIUbzUEVqnKZmZI":
			"Compendium.black-flag.npcs.Actor.Bhgv9Dgx4oMv7noH",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.tI6lREz0xXbwpLuv":
			"Compendium.black-flag.npcs.Actor.Byks5SnzyZS2lLM9",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.gVTpUJU70liiZEtO":
			"Compendium.black-flag.npcs.Actor.C8poa43FQVz7g733",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.2xBI2p3EmzFpGfBN":
			"Compendium.black-flag.npcs.Actor.CHhj6Dc9MioKZUW0",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.NDt1OGqBETnpgjDI":
			"Compendium.black-flag.npcs.Actor.CXZYL33DFVG6GJwL",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.MWTaF42tj3dC1s6w":
			"Compendium.black-flag.npcs.Actor.CaJnEjsHWu9hgyKK",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HIiZ71cuP8yl8liN":
			"Compendium.black-flag.npcs.Actor.Cdi71IHxNif3sV33",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jmCstjvQ7Q1iRpz6":
			"Compendium.black-flag.npcs.Actor.CesKpbFPrfkosm60",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.wW7gKs3U0L4m481U":
			"Compendium.black-flag.npcs.Actor.D57uCaeuo8hdTWAj",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.XpMqpcy2K70mImav":
			"Compendium.black-flag.npcs.Actor.DIozpmms6n4Oy2Lj",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.msTA8dZH1kDkIXYj":
			"Compendium.black-flag.npcs.Actor.DUp2nkLdBa11964x",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.hmhQZ76sYww1aYv4":
			"Compendium.black-flag.npcs.Actor.DbHnyqTe1SirbX1n",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.9XDtfO9S4bbOuMIi":
			"Compendium.black-flag.npcs.Actor.Doo3kyUey8pTbY8K",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.A3qsz8JPCNORRTOV":
			"Compendium.black-flag.npcs.Actor.DsBUbp4BWMKUJeJF",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.8lEOr7TCGjtUhWgg":
			"Compendium.black-flag.npcs.Actor.DwmqCxwUGgJVxj30",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.GO3NKnF4hQheioLX":
			"Compendium.black-flag.npcs.Actor.E1xyqyeEeOjxQfDd",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.nw4fBZPwgqOlwrki":
			"Compendium.black-flag.npcs.Actor.E2GtLSyUX3zyv1iK",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sDUb240K87nZTU1r":
			"Compendium.black-flag.npcs.Actor.E7WUOZSTtaXlxpzg",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HxlDiBpVKrxWilzR":
			"Compendium.black-flag.npcs.Actor.E91VqMOUotcixlqp",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.JfsobFzqn7vjZsj9":
			"Compendium.black-flag.npcs.Actor.EL4NK2bZqTV0erXC",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.KVwo05T2GM49miil":
			"Compendium.black-flag.npcs.Actor.ELOJUXJGpMxWSxdh",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.PO2VE1GIACd0xXXx":
			"Compendium.black-flag.npcs.Actor.EMVh5u9dhoOw0cjR",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.6lorRKK9WK4yvUvq":
			"Compendium.black-flag.npcs.Actor.EPPs9D9dOiv1aMvP",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.7QqOyvzwPshbqxqc":
			"Compendium.black-flag.npcs.Actor.EoPZ2R8diSblHcq5",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.VIkJBidKobuQsRHG":
			"Compendium.black-flag.npcs.Actor.Eq0kPFHAIxVCsRHO",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.nxHYOXqaPKuTDSng":
			"Compendium.black-flag.npcs.Actor.EuzLTBHGHkXp4uEI",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Hjt32yTa8tOAHm8K":
			"Compendium.black-flag.npcs.Actor.F5iAJEkQmX1oCW8z",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.hlBRzzdJYaZJXwfi":
			"Compendium.black-flag.npcs.Actor.F83TtnzrjXEXQ3N7",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.qO24WxfI7zPqFif8":
			"Compendium.black-flag.npcs.Actor.FDxN3ZFZFK1TzVjx",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.bjUNPVfA8uSOyJIl":
			"Compendium.black-flag.npcs.Actor.FFzAbPY1xZBZ9i7V",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.YqsZ4mit5Q8SP0CY":
			"Compendium.black-flag.npcs.Actor.FIdfBlHC564JtPUH",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.yesCrSp5RrWc1ol9":
			"Compendium.black-flag.npcs.Actor.FN3IwIUVWKkhhiF4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.izTZNcFeJYRyKsd1":
			"Compendium.black-flag.npcs.Actor.FSgYGI4PWAYSea0n",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.awgUbS5Rc7UJ0sjy":
			"Compendium.black-flag.npcs.Actor.FZJ6y3tsNnZ6wjFs",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jMFFEgCAoGOxGwFc":
			"Compendium.black-flag.npcs.Actor.FlG5TBMwT6On5d36",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.uK69K7ZqOCGXNxQh":
			"Compendium.black-flag.npcs.Actor.FoI9Kwk09xJJ8TJq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.WihiQ04O60XZHXSJ":
			"Compendium.black-flag.npcs.Actor.Fq8H09xuu7otAUpn",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.4gDQrjsCbcjQCkXr":
			"Compendium.black-flag.npcs.Actor.FuwI4sYfUqwJUCLZ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.5h0hMglnNjaN4Wip":
			"Compendium.black-flag.npcs.Actor.GCLXU9huKDU164WF",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.8JIKtp17DUjJCJOd":
			"Compendium.black-flag.npcs.Actor.GNVzrdU7XykGzIXW",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.rDZOboA3YcHaHmDE":
			"Compendium.black-flag.npcs.Actor.GTo6rb03cdWAZ4lh",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.4x95UhZYanzOQBIm":
			"Compendium.black-flag.npcs.Actor.H6pAKPnTrxJfFJhi",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ilvok2j4Ys7zjeS5":
			"Compendium.black-flag.npcs.Actor.HM8lzmU017IEKutE",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.OnaHbel8cLmycIvw":
			"Compendium.black-flag.npcs.Actor.HQ2jkq8ZZacZwF03",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Teim2Uc5FaEmTF93":
			"Compendium.black-flag.npcs.Actor.HjLzNvpWvHANVJT0",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jvgfL1KwSHTsigT2":
			"Compendium.black-flag.npcs.Actor.HuCHKme4WginEBvZ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.yGbSstgBhBy006mV":
			"Compendium.black-flag.npcs.Actor.HygHNXNR3ltqfGCU",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ZmLZvoJTIGM7ztVU":
			"Compendium.black-flag.npcs.Actor.IM118pSBKG93TdCT",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.JRZWv6AegnprZ1n4":
			"Compendium.black-flag.npcs.Actor.IN6xQ0eaTEGbzbjC",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.AVx4QzLcbr0ikcii":
			"Compendium.black-flag.npcs.Actor.INFGYVVuVhDKEL0g",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.uOJNVscBK4rEzyoD":
			"Compendium.black-flag.npcs.Actor.IQutgcAWWYUWePKs",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HgHLXqcGnd07lvqu":
			"Compendium.black-flag.npcs.Actor.ISXBZMqeLNEI8zmd",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jJMX1iTWir0epaFB":
			"Compendium.black-flag.npcs.Actor.ITGAkxRlWepJr2gF",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ByLHmInyBC5Y74j0":
			"Compendium.black-flag.npcs.Actor.ImTx2hN7pQqGK6fe",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.yFHKLNBBGMjmg20E":
			"Compendium.black-flag.npcs.Actor.Imfc7AYR6TCzVgRl",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.g3e8e7V5BooXSeLo":
			"Compendium.black-flag.npcs.Actor.IsiIz1yjC3Xg29a4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.9vzDWLJejIJtqsAY":
			"Compendium.black-flag.npcs.Actor.Iw4X0SJiYqWIiyy8",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UDoyS1CNcX67kPS1":
			"Compendium.black-flag.npcs.Actor.J4EWVKO4Egps6OtA",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UAzDdV1wnxtpgs0C":
			"Compendium.black-flag.npcs.Actor.JDgmzjnGH4W18u3m",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.0crdJs3BeDniYEx7":
			"Compendium.black-flag.npcs.Actor.JHttBWIKfW7bFVtr",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.dVDhW2kPhuwl5eNP":
			"Compendium.black-flag.npcs.Actor.JKa19JUYxYjD4Tlz",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.VUl8Zv3IDxOSNN1M":
			"Compendium.black-flag.npcs.Actor.JX1vSza5sipBjUjf",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.KDER5KdHroXML5GM":
			"Compendium.black-flag.npcs.Actor.JqdJE9zO1l4PjIgy",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jsKtEtawemj2arci":
			"Compendium.black-flag.npcs.Actor.JxE7IcBM4pJ6sdtY",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.wHHp6MwZElxaq0E5":
			"Compendium.black-flag.npcs.Actor.KyVY9u2LePlCcKDB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.BFZstHfi0baxmNx6":
			"Compendium.black-flag.npcs.Actor.LOgvRwKo3B5hXJSO",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.VQgAOB22p4l3p8tA":
			"Compendium.black-flag.npcs.Actor.M0bMYGaNEtdZQDxn",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.erXy8Tk2DQex25qP":
			"Compendium.black-flag.npcs.Actor.M7mHEq10RcVxYE9V",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Gih40JXfrR4kVoUr":
			"Compendium.black-flag.npcs.Actor.MB5q0gp40gptuY8K",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.r0YD5ZaQ22mUZCeN":
			"Compendium.black-flag.npcs.Actor.MF5NbhwjTV9b2dLB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ueDCdXsSa5jnyMRL":
			"Compendium.black-flag.npcs.Actor.MFiYHnCH5sJ1TMF9",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.CAiVOyUyEIy0rlxA":
			"Compendium.black-flag.npcs.Actor.MYH6C4WPx2UGzfm2",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.poMqcjy3rSLKMpTB":
			"Compendium.black-flag.npcs.Actor.MpMQ6Lo7389vbsbj",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.mUJ8Gx2175qhYaPN":
			"Compendium.black-flag.npcs.Actor.N1mEqhOK8oUD5XG3",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.FhbLe9O9nLMlhF22":
			"Compendium.black-flag.npcs.Actor.NC9LxARgmk2dFhS9",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.QpdjRtFpLswyGKik":
			"Compendium.black-flag.npcs.Actor.NDPrxKEbOwhpsm7t",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.S2uh3aoIAlQ1kjRi":
			"Compendium.black-flag.npcs.Actor.NKLtUM2Rp6LfHico",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.v5UX9VNwR5y1mJmo":
			"Compendium.black-flag.npcs.Actor.NLA3F4q9rFf8w9DN",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Goc4MfKzLtZr7Man":
			"Compendium.black-flag.npcs.Actor.NLKyXyyesFlraxWi",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.h9tksLn9pLljeoob":
			"Compendium.black-flag.npcs.Actor.NRhGNRfvqJrX30id",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.mEIsQBDOeEafi5Kc":
			"Compendium.black-flag.npcs.Actor.NS7UISvgtmDOQ9MI",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.h7zIE6bw8LN2NHxC":
			"Compendium.black-flag.npcs.Actor.NSwzdwp77mjlTHlD",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Pyxadmt6v553oLyh":
			"Compendium.black-flag.npcs.Actor.NbKK3JoT3U4yVgXX",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.qV6VRRvP0IceKudI":
			"Compendium.black-flag.npcs.Actor.Nd0vbYlEDsYMJSk2",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.CkirAVXYhCqLuDi9":
			"Compendium.black-flag.npcs.Actor.NrkJnkJEcByBsqr9",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.PFfhOuJNIw1dMUqI":
			"Compendium.black-flag.npcs.Actor.OFvaU7jGTycWM8sp",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jeyDcPmAXdZVX9EJ":
			"Compendium.black-flag.npcs.Actor.OMX5d94wnbioOWys",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.wNJOg4euAaZh9aL3":
			"Compendium.black-flag.npcs.Actor.OSMsc0YrZ1eUkPz2",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.xxS4ea7ZR4Zy0xVq":
			"Compendium.black-flag.npcs.Actor.PDsnXVO64ew2HMla",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.oX1C9ZnXVhVIzO6M":
			"Compendium.black-flag.npcs.Actor.PIz6OxdTiqdlix0y",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.zqSX9F3i2yHqdEgx":
			"Compendium.black-flag.npcs.Actor.Pb3ANp5eQ5rQdMuO",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.1VcYrovypQisy3G5":
			"Compendium.black-flag.npcs.Actor.PgG1Izz1wtP1AVc1",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.vUuyuRpA3goz6XnL":
			"Compendium.black-flag.npcs.Actor.PgohhJx6393szUlk",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.QHHmvn4B5SDA0otn":
			"Compendium.black-flag.npcs.Actor.PuyGsCyCqiZnH2Zl",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.42rhREi6ZuS2c0n8":
			"Compendium.black-flag.npcs.Actor.PxfSVMywI0tAA2yy",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.2I8EQXmRG9W7X91T":
			"Compendium.black-flag.npcs.Actor.QBvgtZKfIM8xi0We",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.04K7hp4aRLilOToF":
			"Compendium.black-flag.npcs.Actor.QCC1wGo0aUqX9nj5",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.2tthohHl8zNcyucI":
			"Compendium.black-flag.npcs.Actor.QIeRCv66WQ4OuZGw",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.EIQp1oc7OnlbroCI":
			"Compendium.black-flag.npcs.Actor.QPUYtws10izwB41G",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.WQJWoYnxRmLluZez":
			"Compendium.black-flag.npcs.Actor.QbwUREeTjQ2kv29j",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Le9JR4xE3zB3fk8j":
			"Compendium.black-flag.npcs.Actor.QhUdfEtDyVBgsWqJ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.bS83voALAowFEnkv":
			"Compendium.black-flag.npcs.Actor.R02ibrI7r0P2MuYe",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UZ4A79JLsBoITdwg":
			"Compendium.black-flag.npcs.Actor.R6UAoLrMzuXs0rSc",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.VYqytAwAzTSuOTjn":
			"Compendium.black-flag.npcs.Actor.RS2SzdUsZvEAYUDt",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.fMakBiKUCXmwO5wO":
			"Compendium.black-flag.npcs.Actor.RgWTEI3qCEhH5f5p",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.lvJrzSKFfYsgeYTo":
			"Compendium.black-flag.npcs.Actor.Rstx00Mw1KHQ0Uau",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.wucjuYX6MwiG5c8E":
			"Compendium.black-flag.npcs.Actor.SOk3xmj8v4SZrsT1",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.w1sSced232MUUm1Z":
			"Compendium.black-flag.npcs.Actor.SXdg3MWnVxlg1urO",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.gPMjxuuvUHwuXevc":
			"Compendium.black-flag.npcs.Actor.SjxwoQ8AHbO3zHoU",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.N26jHGFtTXiHJPvC":
			"Compendium.black-flag.npcs.Actor.SkO0ZyfahsSJ0VGt",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.TmlQaRogztAV7jwn":
			"Compendium.black-flag.npcs.Actor.Ss0Bwrs6FOveDoFy",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.PodGfZc1k6sp5slf":
			"Compendium.black-flag.npcs.Actor.TQUgLlfRbjhyzVvR",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Fx4ESN5CAVmYEVU6":
			"Compendium.black-flag.npcs.Actor.TQlCeRlqoGzuef9j",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.pQYXPzSXcfPw7rVt":
			"Compendium.black-flag.npcs.Actor.TY6IN0DHMzsqUYVk",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.lxXkTp6dYeDImqCv":
			"Compendium.black-flag.npcs.Actor.U301vMUDHMsilO8e",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.TObsyirpxiYFXl8K":
			"Compendium.black-flag.npcs.Actor.U97WXv0e1InYdlFY",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.dWoMxuPpIwlQDYAX":
			"Compendium.black-flag.npcs.Actor.UBFzn2d2RnVgO8Rl",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.P3UNTiAmn64plrnt":
			"Compendium.black-flag.npcs.Actor.UDelAhYWBUG6UB65",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.uz4svvqpgRdoXXtZ":
			"Compendium.black-flag.npcs.Actor.UHqydMVavWYtY4d3",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.o03D0YvjNIvwGTED":
			"Compendium.black-flag.npcs.Actor.Ud4a8hMgKHtjSSde",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.nQwKHqzKbP6gDLGi":
			"Compendium.black-flag.npcs.Actor.UdDVSYvYVpizaE4I",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.vitUaDjoTiByRlgT":
			"Compendium.black-flag.npcs.Actor.Ue1i1lK4SQAqR3lq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.dSIa31EfarSWcB5t":
			"Compendium.black-flag.npcs.Actor.UeYX37CmSwDYEIo5",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.YrZuw5BeFj9obWcm":
			"Compendium.black-flag.npcs.Actor.V0hoY7QNVvQwQDCB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.rEb6s31LaUoFvGDz":
			"Compendium.black-flag.npcs.Actor.V6nG6JPoYtPbI1Ss",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.W4vQapOttm43LoJU":
			"Compendium.black-flag.npcs.Actor.V8ccZwy2rPAl67gB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.1ixlvxOVSYnWQGtU":
			"Compendium.black-flag.npcs.Actor.VWvHuk0QUHjoAPkC",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.iopOSQXnBVqwsvXz":
			"Compendium.black-flag.npcs.Actor.VeVmo85SztJhGZsN",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.0KkLaWOyOUhPLfTn":
			"Compendium.black-flag.npcs.Actor.VgI9TWuZwWjD2xgg",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.WYEYTQljEF2YMF4j":
			"Compendium.black-flag.npcs.Actor.VhgEQGMdXxpOUfXL",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Ph2UYOuMPpxEikrO":
			"Compendium.black-flag.npcs.Actor.W9ftI3mrL0czngCq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.9puI2Q0vfcj9LfEH":
			"Compendium.black-flag.npcs.Actor.WBg1MmOJneyRRKu8",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jcB4Lyu5JIk15eZG":
			"Compendium.black-flag.npcs.Actor.WJQwmBf1BFyGbIbP",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ulisaOWYriVtDUxA":
			"Compendium.black-flag.npcs.Actor.WMceKrllLfWXxPU4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.efxNVpDuzkBAnjGW":
			"Compendium.black-flag.npcs.Actor.WPrjdve77A9SA94h",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.w0wchIrkh5xU1YYj":
			"Compendium.black-flag.npcs.Actor.WaqJiuEog6C2Sjgw",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.DmHm2pUTgf1BcJsA":
			"Compendium.black-flag.npcs.Actor.WdBjJZWKexQ9yWKE",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.foo9T1hrJEGW7CjG":
			"Compendium.black-flag.npcs.Actor.WnWvUNVhVxcyfymA",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.wziCRFPh3XaZz5vL":
			"Compendium.black-flag.npcs.Actor.Wu2QaZI38nWZEZtb",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Ut8VwQPVs2ZJScx9":
			"Compendium.black-flag.npcs.Actor.X0zlkGwxdiwMe2VR",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.9S2Yfkhh0H5j27GY":
			"Compendium.black-flag.npcs.Actor.X82CDCyHgR41wdQE",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UuHYMxUkRVfXJo5B":
			"Compendium.black-flag.npcs.Actor.XI5EEwMBVeGGqYUA",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.i0Nn5KSz7yykIzUo":
			"Compendium.black-flag.npcs.Actor.XLurGEHU0ev1Tcsj",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.DS2KM0HmGiFpy3YF":
			"Compendium.black-flag.npcs.Actor.XY0ee4F1zQNR21Wy",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sDxmbONKiohKIvtq":
			"Compendium.black-flag.npcs.Actor.XZLnelxGPTG9ndG7",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.vhdEfqdzheEjB4sN":
			"Compendium.black-flag.npcs.Actor.Xax43OMCHOc2UUoc",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.cWfHn437bHzjZKtq":
			"Compendium.black-flag.npcs.Actor.XfSCmCndblO973ag",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3IUwvaPy4DBOQaEb":
			"Compendium.black-flag.npcs.Actor.XhTebmzMEmxnMYX7",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.om2QskCe08driuyo":
			"Compendium.black-flag.npcs.Actor.YVG4vXSOTxY7HfMJ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UvzX3uUj1N8rxcm2":
			"Compendium.black-flag.npcs.Actor.YZB7WaKKKDjkd5la",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.f9KDVyADp1AY4B9a":
			"Compendium.black-flag.npcs.Actor.Yi7b5kSrOjaBWcz7",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.LH0XRcQxQHUr5QEg":
			"Compendium.black-flag.npcs.Actor.Yu69oqsjr4GnVygA",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.waK5T2RfmyiRryL0":
			"Compendium.black-flag.npcs.Actor.Z7Im1Pl2ugOycad7",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Mw1SWH3eLJLbm88s":
			"Compendium.black-flag.npcs.Actor.Za8SWZT6BRyG18Kx",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.NseZbQVdJSuiMLIw":
			"Compendium.black-flag.npcs.Actor.ZbOSkmu1Vo1l6UyP",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.g61ksVZoPvnF8ksU":
			"Compendium.black-flag.npcs.Actor.ZjUi1rotZtqrOb01",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.8eQULmnILzf8VIaD":
			"Compendium.black-flag.npcs.Actor.ZzDX43iwJ5GE57f4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.cIgcogNVdVICiMnu":
			"Compendium.black-flag.npcs.Actor.a7dzJIh3xbXeEz21",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.K1ZUbUg44jIgyLfv":
			"Compendium.black-flag.npcs.Actor.aHutizsTtDFfX1xw",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.GrspuvDT8VmvwAuD":
			"Compendium.black-flag.npcs.Actor.aODuTJFvfNhI76YH",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.apQOibmdO07O9JUj":
			"Compendium.black-flag.npcs.Actor.asAvxBBPVAmlLVNB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.fiVu82tYM9GRYhwn":
			"Compendium.black-flag.npcs.Actor.b0zD8sn4N4SwQZWn",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.FHEPIhOkVeXAbZQf":
			"Compendium.black-flag.npcs.Actor.b3IuKxZgDZFB60TD",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.TzhpfrmGr5Cmb4wr":
			"Compendium.black-flag.npcs.Actor.b6WyT2uZ2s0hH5EQ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.mrzXMVgTTOKs3idf":
			"Compendium.black-flag.npcs.Actor.bWknOpKfG47YpIah",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.19gNcUBKwfHf9tgE":
			"Compendium.black-flag.npcs.Actor.bdVcAUcSnPMT6ZnL",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Jgwv1BbLyNY3Guix":
			"Compendium.black-flag.npcs.Actor.bk9J56h4Ng6K6mLI",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.in5Or33eZYZnjmBY":
			"Compendium.black-flag.npcs.Actor.brp0QMrUtl7IIMuX",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sAlKtDJ9Iq6m60TB":
			"Compendium.black-flag.npcs.Actor.buqFMdIMMReaxLgL",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.4c8OU0wppABeDwsB":
			"Compendium.black-flag.npcs.Actor.cB8DGxkbUhEiLB1w",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UjSJPi4f6SSi2X8b":
			"Compendium.black-flag.npcs.Actor.cSgTzu79oKyZAOLG",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Dq8YEToNEwx6kUSG":
			"Compendium.black-flag.npcs.Actor.cZQEGg1n82DtB1B7",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.phyQEH3HvxBqNKq7":
			"Compendium.black-flag.npcs.Actor.cgnLl6eA2TXlpDWA",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.QZ1gndKMQmX8Iisk":
			"Compendium.black-flag.npcs.Actor.ciX8E1MCTf6MsoLz",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sgP6OMZFvvQNLXtC":
			"Compendium.black-flag.npcs.Actor.ck0kqumkVqWznctK",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.qFP81iGnliYj2alW":
			"Compendium.black-flag.npcs.Actor.clrjqjIGpwSbKDdr",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.KELhMhGeiYKwQNeA":
			"Compendium.black-flag.npcs.Actor.cquozeSlJD3zYlL8",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.1w76HzQMA8rBspFW":
			"Compendium.black-flag.npcs.Actor.cw0jtRfsxiGPSxVg",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.mFWXbgqPLgXl2kRT":
			"Compendium.black-flag.npcs.Actor.cwmRactFb8d6yQRn",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.w5Ro2ub0HPGYR8X4":
			"Compendium.black-flag.npcs.Actor.d5lMdSG98vqJO3xy",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.n97FjM0gzr6MkPOE":
			"Compendium.black-flag.npcs.Actor.dfInJBbszNjFdUtc",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.SzkPHt3tdXOFPLbj":
			"Compendium.black-flag.npcs.Actor.eKoP33PXVPjGlpYM",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.RqzOHuGw3dMSV3yQ":
			"Compendium.black-flag.npcs.Actor.eqOkida23HMGsEkC",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.zvALiWxXLJ6zwJU7":
			"Compendium.black-flag.npcs.Actor.euCGJRfmdRCsdnZs",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.csupVsyrd1FkrGO7":
			"Compendium.black-flag.npcs.Actor.f8OZ3qR5dktPErhU",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.g6A7BlrfD3GwWKR9":
			"Compendium.black-flag.npcs.Actor.fp7eFxkfnQqq5GJZ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.nqLpQUGMhYLzIXWN":
			"Compendium.black-flag.npcs.Actor.g586vFs1XriKy1Al",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ALVbZLcZDuKOj14Q":
			"Compendium.black-flag.npcs.Actor.g7zcm2McnEiyfZKC",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sPQkw1lZ7sbNJtXK":
			"Compendium.black-flag.npcs.Actor.gHi8SHUcg2rmuJC4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.tqHuUlJtEE8ivxeG":
			"Compendium.black-flag.npcs.Actor.gWWEn9hsrNGlYi7Z",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UlS7Gk5jT7WEU7id":
			"Compendium.black-flag.npcs.Actor.ggoxWnq9zRR4EUom",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.5WiJTkoHGKYQDblH":
			"Compendium.black-flag.npcs.Actor.h1hoa6N6IlypbFz0",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.5eGrt6Xrn5J3SCFt":
			"Compendium.black-flag.npcs.Actor.hOgnjyo11UFsresY",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.4833Et4DRMHt073q":
			"Compendium.black-flag.npcs.Actor.hiQXL3rtSIZsrKui",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.tnWWozYBmCQ7bJPi":
			"Compendium.black-flag.npcs.Actor.hpAmWmT3s3VrflWl",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.QBld0sZEnXtrAjiK":
			"Compendium.black-flag.npcs.Actor.i3Uu10KX5tvmseAQ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3OJGopFO0cw5Mer6":
			"Compendium.black-flag.npcs.Actor.i4NFjO6EY2U2Rc8g",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.KRhqSnlO4bD2W39h":
			"Compendium.black-flag.npcs.Actor.i5ZMW53YK1mODw9r",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.RRuostw1tIx3qFzg":
			"Compendium.black-flag.npcs.Actor.iGeIfiy7aIAg7JV5",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ydIgQDYLboTNpbc0":
			"Compendium.black-flag.npcs.Actor.iPE1p3z5N9774Aqz",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.xqC38manlqV2g6Bg":
			"Compendium.black-flag.npcs.Actor.ioptmAxgvplXdxMJ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.y25rp8YTpk7E17ii":
			"Compendium.black-flag.npcs.Actor.iyWpO1bTYA1b3B7b",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UgTJarNfbXeUp83t":
			"Compendium.black-flag.npcs.Actor.j02ykQqDOZVgN8MV",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.M5C9HJPqBudEM4tK":
			"Compendium.black-flag.npcs.Actor.jH8xObIbnEmk6Sjx",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.zwSZK8DNy3LHPP1e":
			"Compendium.black-flag.npcs.Actor.jrFETGwaRC12Gcgo",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.4NWGDo8dWELRjvTX":
			"Compendium.black-flag.npcs.Actor.jujAFfwxEOBwL2Us",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.86FQ5oEKeCXg7A3l":
			"Compendium.black-flag.npcs.Actor.jzd7C2z0p2vcCxLU",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UYyLgRglThNxpyGV":
			"Compendium.black-flag.npcs.Actor.kSCNogXBHBJCc2Lj",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.VaI1ZE2oan4EyNGH":
			"Compendium.black-flag.npcs.Actor.kUqTx9G9dCcGom8H",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.0bN59SHOeVkBdCS9":
			"Compendium.black-flag.npcs.Actor.kXwQIPBSeUCmhroJ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.KSZBvrZnwLYTVcaY":
			"Compendium.black-flag.npcs.Actor.knXlk6o8PxOdbDI4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.r1mNo4BD70pbA0kj":
			"Compendium.black-flag.npcs.Actor.l5Bd7urAFSOCktWs",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.cpei2Ltqggu8EGKh":
			"Compendium.black-flag.npcs.Actor.lPSgL3IEmYJb2FTm",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.OpybaPKKfV7P3vvm":
			"Compendium.black-flag.npcs.Actor.mMwrvECrgnTWkgSR",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3rMnLACeMWi9SGWI":
			"Compendium.black-flag.npcs.Actor.mRLx4ou4JQf5IwMb",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Ilb52LQDjo2zAPBS":
			"Compendium.black-flag.npcs.Actor.mdERCYbI7VnDABew",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.inc27hpTUmrAAJao":
			"Compendium.black-flag.npcs.Actor.n7MQrAOMaaGucS5J",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.AdvVdNpBLIrkTKMd":
			"Compendium.black-flag.npcs.Actor.nI8fNmp3yL83G8fR",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.4YE2zS05Naljo7G5":
			"Compendium.black-flag.npcs.Actor.nVo8nTfyk8DkPv3p",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.poTQVr316nY5wO2w":
			"Compendium.black-flag.npcs.Actor.naDs3W5YhTHbr1ej",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.y24kqStOgMTIzZYo":
			"Compendium.black-flag.npcs.Actor.net7utpz7v44amQ4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jXd3NxlDtHJJs11r":
			"Compendium.black-flag.npcs.Actor.oRKs6zIzuH0mO63T",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HjPDsuf859A8SHes":
			"Compendium.black-flag.npcs.Actor.ofeQtVfgvGIk6L0e",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.hR0LXas8LMP6oA1N":
			"Compendium.black-flag.npcs.Actor.oissj1hsaDwgvw3k",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.D77Jj3SqXOgzFYvh":
			"Compendium.black-flag.npcs.Actor.opwZgKqVqntUSyxN",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.1ImbqMffnFLT0YyB":
			"Compendium.black-flag.npcs.Actor.ov0XmnwLkhoR2PUS",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Bfg7QYOn4xpbYjfP":
			"Compendium.black-flag.npcs.Actor.p3pNpEqq7uMS4OIV",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.UzUqDlLd8N2HqrP8":
			"Compendium.black-flag.npcs.Actor.pEqya9TxqRPwo1JI",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.fSq6ZPSOSQkIPr9T":
			"Compendium.black-flag.npcs.Actor.pHh8GddnzZYbiKQR",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.w2Q3brSoIgqoe5dH":
			"Compendium.black-flag.npcs.Actor.pIR9tOfVD3TBs02T",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3xg4QNruvBchYDzC":
			"Compendium.black-flag.npcs.Actor.pLJ9uARWkhzv5RP4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.8hatMQYALXJqiUnW":
			"Compendium.black-flag.npcs.Actor.pMDqNFx7VKgC3SUZ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Ar7xRwRTKaBWGIMx":
			"Compendium.black-flag.npcs.Actor.pnMVYeOXRmIXdm2z",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.76Me6VcQ461FFvAJ":
			"Compendium.black-flag.npcs.Actor.puJPu9Fl8PI81zuh",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.xj9sQNUcapS5bQEU":
			"Compendium.black-flag.npcs.Actor.pyDYHRdZzv3Br8wM",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.g8fjTkEb6UEqGD0f":
			"Compendium.black-flag.npcs.Actor.qQcu0AgHe762M5Gh",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Uwhl27mKQmB2nV2B":
			"Compendium.black-flag.npcs.Actor.qvC6VqO6BfDUg0sf",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.44l71RDORCEN7AIA":
			"Compendium.black-flag.npcs.Actor.r92GuCwB5hkH46GP",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.xQtbvxfWwIRSmsUl":
			"Compendium.black-flag.npcs.Actor.rABx4QexdSc6vTsq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Yi8ALRTei8diYLpQ":
			"Compendium.black-flag.npcs.Actor.rEjsBo7fnpeE7VyE",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.9NNfvbSmfQIbSKFl":
			"Compendium.black-flag.npcs.Actor.rV9gDP0hIqmPm5ri",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.9vTeMPtBrkCKKWXz":
			"Compendium.black-flag.npcs.Actor.rZOCoED4brskz3Kp",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.mqnIiQQbY76f0M5N":
			"Compendium.black-flag.npcs.Actor.rgZKxFrXIhvhMoPe",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jpYV3kUeRc2wDTEZ":
			"Compendium.black-flag.npcs.Actor.sC5LVxumiNuA8EJH",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.XQVgMo1YBsPLfNIR":
			"Compendium.black-flag.npcs.Actor.sEpsqtVJdrJy5VQS",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Nx3vzPiXSysYOZSz":
			"Compendium.black-flag.npcs.Actor.shCcNmE8Rqfy6JIf",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.k0IixcKDbBhyYOCG":
			"Compendium.black-flag.npcs.Actor.shpqWu1QjD5eclBW",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.2nI2v5A6Y37wdUdK":
			"Compendium.black-flag.npcs.Actor.skR6NOTFWg20bng1",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.EUWcVtrvCMrbAC9T":
			"Compendium.black-flag.npcs.Actor.spxoi6GkVFiLmhPB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.0RnEUV8shkrk7yrP":
			"Compendium.black-flag.npcs.Actor.t6Hq3bNVZrkPPGxa",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.TsKwxtv3C4zWBsEV":
			"Compendium.black-flag.npcs.Actor.tClMSNYOydhPEtCV",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.l3dnjlxNXCcQiGPW":
			"Compendium.black-flag.npcs.Actor.tI2hsbBl6skqEkOp",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.REeq8PgajdfxsKGs":
			"Compendium.black-flag.npcs.Actor.tPJ2ypkwT92mglS6",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.t2IG9p2jxdXGEjny":
			"Compendium.black-flag.npcs.Actor.tekf4vWWHqDYFv8k",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3WPWSaK2rSwFCVtx":
			"Compendium.black-flag.npcs.Actor.tgA4k8Lbt4DN3soa",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.PVVqAIyhI9CvmQ6D":
			"Compendium.black-flag.npcs.Actor.th8XoqIxyhbFl55A",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.AbNTdipV1SMUIM0P":
			"Compendium.black-flag.npcs.Actor.uoDsMggejKynGeD9",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.weDsSe6WFEnWSgBw":
			"Compendium.black-flag.npcs.Actor.usBkwcEYxNPK7eXq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.U6s0o0HjC1YAadbd":
			"Compendium.black-flag.npcs.Actor.vGbowahPWqSQNJIj",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.oodjqXhuaDYJyxn3":
			"Compendium.black-flag.npcs.Actor.vPMpVsckn4SlfL2e",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Qci6BeSOEudLpDgv":
			"Compendium.black-flag.npcs.Actor.vQ7XQl5sZYsxpMnB",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.akPsOv3cFGffQjNt":
			"Compendium.black-flag.npcs.Actor.vU6tpBRh3XgEJCQS",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.pU1WCHTfqLWmoCI1":
			"Compendium.black-flag.npcs.Actor.vYLiHfYOHm9CXs9I",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.GA3E6TWY3u5PGVKa":
			"Compendium.black-flag.npcs.Actor.vdO9WvllTWSJTxO5",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.m8KzhZ4LUNeGYmUz":
			"Compendium.black-flag.npcs.Actor.viZtu4bAm6ZvKmIN",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.HjlGsxjpUZ1Dn3nb":
			"Compendium.black-flag.npcs.Actor.vlB6jIBlQqXBM2QF",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Hphga67uFjQ7pPVV":
			"Compendium.black-flag.npcs.Actor.vlOJ3k4XJoZhhkdK",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Yf4sTVl2mSLvMVRB":
			"Compendium.black-flag.npcs.Actor.vsJSzta9m9xgEXbW",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.QeljZDquBzAAd0DX":
			"Compendium.black-flag.npcs.Actor.vyegR5HG5tDlmfxn",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.D3ifP7BdJ2JiPB0p":
			"Compendium.black-flag.npcs.Actor.w1Kv6iA09ahXHClR",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.044rJ4pwxJf91Rji":
			"Compendium.black-flag.npcs.Actor.w6hV6Lspei6Bb5r5",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3EMBDpwzOAhAFhW5":
			"Compendium.black-flag.npcs.Actor.wRv1Bu617cEACE6Q",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.T8VEBtELs5cG9L3t":
			"Compendium.black-flag.npcs.Actor.wV7iTQXMeylQ1GLY",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ZACpAJBzhJhXQ5lD":
			"Compendium.black-flag.npcs.Actor.wdVwwqWDYfJ7V1xa",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.nRFqKtVk5fCTgbgH":
			"Compendium.black-flag.npcs.Actor.wnnX3hr0Zo3jRtiY",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3uO24tvOGlqwFJvQ":
			"Compendium.black-flag.npcs.Actor.wsYhKmcZQGjpoxBM",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.7CQzEZizeSIcSP7O":
			"Compendium.black-flag.npcs.Actor.x0GMYLNpOmSzUC2w",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.821zAsnVWkkdEsu9":
			"Compendium.black-flag.npcs.Actor.xD6N8A8ZlTwNfmZ9",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.nwFf0rAmXKAJG1Qe":
			"Compendium.black-flag.npcs.Actor.xV8xaPrWzlA2iSj8",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.zO19wD6ZiqJu5zAj":
			"Compendium.black-flag.npcs.Actor.xb6xkLufGgW66ADy",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.17hjCetGSGHmLoYV":
			"Compendium.black-flag.npcs.Actor.xi88QgskH6ueJ6Ma",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Ml5ccFxAdITuK4Kw":
			"Compendium.black-flag.npcs.Actor.xovBE0pXygwryVLa",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.J6WSA8wUKHVif124":
			"Compendium.black-flag.npcs.Actor.xr4I1f60XZGqtaOe",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.sWFvWjrCZ5A8GeWx":
			"Compendium.black-flag.npcs.Actor.yE6PgxHymFFfBNSu",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.plkKNaK7zo2ZraHj":
			"Compendium.black-flag.npcs.Actor.yU15RNDaUzQaM4cF",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.iUOk8bqGY6ivZOSB":
			"Compendium.black-flag.npcs.Actor.yfli1mZGZTLdPxEq",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.0UchZ8TI5tG0vASc":
			"Compendium.black-flag.npcs.Actor.yhAnGtwttTdrbFxU",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.nN68OTU73RVAho3A":
			"Compendium.black-flag.npcs.Actor.yjcpvMcDeS82FWr4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.3WSCeiAurwKM2Kml":
			"Compendium.black-flag.npcs.Actor.yjd5EqF2xIbyppga",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.68Yn8SwPGkTHabhm":
			"Compendium.black-flag.npcs.Actor.ynfb6jhulpdR0d6D",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.d8vo0lmoCVu23As3":
			"Compendium.black-flag.npcs.Actor.z3MG8r2SDVnujWtJ",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.EBUashyUhb5XzNot":
			"Compendium.black-flag.npcs.Actor.z5c9ixFNcqW4Tgf4",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.jx4iRC7XoImafcxL":
			"Compendium.black-flag.npcs.Actor.zXP6iOGQpuxcyqp1",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.0MVm84PMtYWWhKOK":
			"Compendium.black-flag.npcs.Actor.zxugaPCgwV1Sp8uC",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.ayi4T3TKqqkrffGy":
			"Compendium.black-flag.npcs.Actor.zzQznETcwztvK2aV",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.qjYoG3uhPSTNDO6t":
			"Compendium.black-flag.npcs.Actor.3JVwDBkdsUvoi4fs",
		"Compendium.kp-tov-monster-vault.kp-tov-mv-bestiary.Actor.Ra8zQs38aWHUpbVs":
			"Compendium.black-flag.npcs.Actor.5j6yqkzmckGvlHbe"
	}
};
